package View.Cards;

import Utils.ManipularArquivos;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author AYU7-WN
 */
public class CardLembrete extends javax.swing.JPanel {

    private final String path = System.getProperty("user.dir");
    private File file;

    /**
     * Creates new form CardLembrete
     *
     * @param file
     */
    public CardLembrete(File file) {
        initComponents();

        this.file = file;

        if (file != null) {
            jTextArea1.setText(new ManipularArquivos().LerArquivo(file));
            lbExcluir.setEnabled(true);
            jTextArea1.setToolTipText(file.getName().replace(".txt", ""));
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbExcluir = new javax.swing.JLabel();
        lbOk = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(255, 255, 255));
        setOpaque(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setMaximumSize(new java.awt.Dimension(130, 180));
        jPanel1.setMinimumSize(new java.awt.Dimension(130, 180));
        jPanel1.setPreferredSize(new java.awt.Dimension(130, 180));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbExcluir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/icons8_Cancel_18px.png"))); // NOI18N
        lbExcluir.setToolTipText("Excluir");
        lbExcluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbExcluir.setEnabled(false);
        lbExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbExcluirMouseClicked(evt);
            }
        });
        jPanel1.add(lbExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 20, 20));

        lbOk.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbOk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/icons8_Ok_18px.png"))); // NOI18N
        lbOk.setToolTipText("Salvar");
        lbOk.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbOk.setEnabled(false);
        lbOk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbOkMouseClicked(evt);
            }
        });
        jPanel1.add(lbOk, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 20, 20));

        jTextArea1.setBackground(new java.awt.Color(255, 255, 153));
        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setBorder(null);
        jTextArea1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextArea1KeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 140));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lbOkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbOkMouseClicked
        // TODO add your handling code here:

        ManipularArquivos grav = new ManipularArquivos();

        if (file == null) {
            ImageIcon ico = new ImageIcon(getClass().getResource("/Resource/icons8_Save_32px.png"));
            String nome = (String) JOptionPane.showInputDialog(null, "Nome do Lembrete",
                    "Lembrete", JOptionPane.YES_NO_OPTION, ico, null, null);

            if (nome != null) {
                file = new File(path + "/lembretes/" + nome + ".txt");
                if (grav.GravarArquivo(file, jTextArea1.getText(), false)) {
                    lbOk.setEnabled(false);
                    lbExcluir.setEnabled(true);
                }
            }

        } else if (grav.GravarArquivo(file, jTextArea1.getText(), false)) {
            lbOk.setEnabled(false);
        }


    }//GEN-LAST:event_lbOkMouseClicked

    private void lbExcluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbExcluirMouseClicked
        // TODO add your handling code here:

        if (lbExcluir.isEnabled()) {
            ImageIcon ico = new ImageIcon(getClass().getResource("/Resource/icons8_Minus_32px.png"));
            int op = JOptionPane.showConfirmDialog(null, "Deseja Excluir esse Lembrete?\n" + file.getName(), "EXCLUIR",
                    JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, ico);

            if (op == JOptionPane.YES_OPTION) {
                System.gc();
                if (file.delete()) {
                    jTextArea1.setEnabled(false);
                    lbOk.setEnabled(false);
                    lbExcluir.setEnabled(false);
                }
            }
        }


    }//GEN-LAST:event_lbExcluirMouseClicked

    private void jTextArea1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextArea1KeyReleased
        // TODO add your handling code here:
        lbOk.setEnabled(true);
    }//GEN-LAST:event_jTextArea1KeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lbExcluir;
    private javax.swing.JLabel lbOk;
    // End of variables declaration//GEN-END:variables
}
